### ISSUE TITLE
Bug: Error thrown when I install Restya latest stable version

### ISSUE THREAD

**Issue by theshades** [RestyaPlatform/board#1175]
Greetings!
I have installed the latest and greatest stable version and I am seeing the following errors:

```
: PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/restyaboard/server/php/libs/core.php:197
Stack trace:
#0 /var/www/restyaboard/server/php/libs/core.php(289): curlExecute('http://restya.c...', 'post', Array, 'plain')
#1 /var/www/restyaboard/server/php/bootstrap.php(50): doPost('http://restya.c...', Array)
#2 /var/www/restyaboard/server/php/R/r.php(5374): main()
#3 {main}
  thrown in /var/www/restyaboard/server/php/libs/core.php on line 197" while reading response header from upstream, client: 172.19.130.86, server: example.com, request: "GET /api/v1/oauth.json?_=1494373824455 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "172.19.130.237", referrer: "https://172.19.130.237/"
```
Can you let me know the cause of this? I am not familar with fpm enough to diagnose it.

Thanks 

Justin

Working installer version as of this post: https://github.com/ShadeySecurity/restyaboard-ansible/tree/e955284c1de7360cec8fc8145f1546f943213367

**Comment by theshades** [comment]
Figured out the install script (and as such my ansible script) was missing php7.0-curl library install. Seeing if it works now.
