### ISSUE TITLE
While adding card, console error thrown for current user

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3678]
## Expected Behavior
While adding card, console error thrown for current user

## Current Behavior
While adding card, console error thrown for current user

```
SyntaxError: Unexpected end of JSON input
  at Object.parse(<anonymous>)
  at Array.<anonymous>(/apps/r_custom_fields/js/app.js:4:13991)
  at fireResponseCallbacks(/js/default.cache.8d3b5ded.js:1:8413)

```

**Comment by sridhar391** [comment]
please set R_DEBUG as false on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15
