### ISSUE TITLE
While updating user about other user actions, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3679]
## Expected Behavior
While updating user about other user actions, console error thrown

## Current Behavior
While updating user about other user actions, console error thrown

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
  at ? (/apps/r_custom_fields/js/app.js:4:13991)
  at fireResponseCallbacks(/js/default.cache.8d3b5ded.js:1:8413)

```

**Comment by sridhar391** [comment]
please set R_DEBUG as false on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15
