### ISSUE TITLE
While loading the activity, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3688]
## Expected Behavior
While loading the activity, console error thrown

## Current Behavior
While loading the activity, console error thrown

```
TypeError: a is null
  at makeLink(/js/default.cache.8d3b5ded.js:1:3540)
  at this.JST["templates/activity"](/js/default.cache.8d3b5ded.js:48:6657)
  at render(/js/default.cache.8d3b5ded.js:69:8720)
  at success(/js/default.cache.8d3b5ded.js:74:15840)
  at save/d.success(/js/default.cache.8d3b
```

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
