### ISSUE TITLE
While loading the insights, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3689]
## Expected Behavior
While loading the insights, console error thrown

## Current Behavior
While loading the insights, console error thrown

```
TypeError: m is null
  at a.attr(/apps/r_insights/lib/highcharts.js:222:31)
  at getContainer(/apps/r_insights/lib/highcharts.js:5338:18)
```

**Comment by sridhar391** [comment]
Fixed the above issue in the Insights app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
