### ISSUE TITLE
While viewing the boards list of the particular organization, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3691]
## Expected Behavior
While viewing the boards list of the particular organization, console error thrown

## Current Behavior
While viewing the boards list of the particular organization, console error thrown

```
TypeError: this.$el is undefined
  at render(/js/default.cache.8d3b5ded.js:82:13013)
  at k(/js/default.cache.8d3b5ded.js:11:16318)
  at trigger(/js/default.cache.8d3b5ded.js:11:15578)
```

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps
