### ISSUE TITLE
While adding the card checklist, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3692]
## Expected Behavior
While adding the card checklist, console error thrown

## Current Behavior
While adding the card checklist, console error thrown

```
TypeError: undefined is not an object (evaluating 'a.attributes')
  at next(/js/default.cache.8d3b5ded.js:47:26834)
  at moveAfter(/js/default.cache.8d3b5ded.js:47:14859)
  at itemSort(/js/default.cache.8d3b5ded.js:77:29495)
  at itemSort([native code])
```

```
TypeError: a is undefined
  at next(/js/default.cache.8d3b5ded.js:47:26820)
  at moveAfter(/js/default.cache.8d3b5ded.js:47:14855)
  at itemSort(/js/default.cache.8d3b5ded.js:77:29486)
  at dispatch(/js/default.cache.8d3b5ded.js:2:14485)
  at h(/js/default.cache.8d3b5ded.js:2:10414)
```

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
