### ISSUE TITLE
While adding card, console error thrown for current user

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3696]
## Expected Behavior
While adding card, console error thrown for current user

## Current Behavior
While adding card, console error thrown for current user

```
TypeError: undefined is not an object (evaluating 'd.activity.created')
  at success(/js/default.cache.8d3b5ded.js:68:28683)
  at ? (/js/default.cache.8d3b5ded.js:11:19479)
  at ? (/js/default.cache.8d3b5ded.js:86:26756)
```
```
TypeError: Cannot read property 'position' of undefined
  at J.d.addCard(/js/default.cache.8d3b5ded.js:68:28089)
  at HTMLDivElement.dispatch(/js/default.cache.8d3b5ded.js:2:14485)
  at HTMLDivElement.h(/js/default.cache.8d3b5ded.js:2:10414)
```

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
