### ISSUE TITLE
While loading the activities in the modal card, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3701]
## Expected Behavior
While loading the activities in the modal card, console error thrown

## Current Behavior
While loading the activities in the modal card, console error thrown

```
TypeError: Cannot read property 'comment' of null
  at activityCommentReplace(/js/default.cache.8d3b5ded.js:1:4043)
  at ? (/js/default.cache.8d3b5ded.js:77:24518)
  at Function.o.each.o.forEach(/js/default.cache.8d3b5ded.js:11:395)
  at success(/js/default.cache.8d3b5ded.js:77:24486)
```

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
