### ISSUE TITLE
this._atop is null console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3703]
## Expected Behavior
this._atop is null console error thrown

## Current Behavior
this._atop is null console error thrown

```
TypeError: this._atop is null
  at k</a.prototype.silence(/js/default.cache.8d3b5ded.js:41:13385)
  at initialize(/js/default.cache.8d3b5ded.js:66:10766)
  at b.View(/js/default.cache.8d3b5ded.js:11:26103)
  at J/d<(/js/default.cache.8d3b5ded.js:12:1203)
  at J/d<(/js/default.cache.8d3b5ded.js:12:1203)
  at J/d<(/js/default.cache.8d3b5ded.js:12:1203)
```

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps
